# Generated by Django 4.2.4 on 2023-08-16 06:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0002_alter_member_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLocation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('radius', models.FloatField(default=50.0)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systemlocation', to='roles.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LocationSettings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('applicable_start_date', models.DateField()),
                ('applicable_end_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locationsettings', to='roles.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationsettings', to='roles.organization')),
                ('system_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationsettings', to='location.systemlocation')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_locationsettings', to='roles.member')),
            ],
        ),
    ]
