# Generated by Django 4.2.4 on 2023-08-16 06:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0002_alter_member_organization'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberScan',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('date_time', models.DateTimeField()),
                ('latitude', models.CharField(max_length=200, null=True)),
                ('longitude', models.CharField(max_length=200, null=True)),
                ('scan_type', models.CharField(choices=[('checkin', 'checkin'), ('checkout', 'checkout')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberscan', to='roles.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberscan', to='roles.organization')),
                ('system_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberscan', to='location.systemlocation')),
            ],
        ),
    ]
