# Generated by Django 4.2.4 on 2023-08-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberscan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberscan',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='memberscan',
            name='latitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberscan',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberscan',
            name='scan_type',
            field=models.CharField(choices=[('checkin', 'checkin'), ('checkout', 'checkout')], max_length=15, null=True),
        ),
    ]
