# Generated by Django 4.2.4 on 2023-08-22 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_alter_shiftschedulelog_location_settings'),
        ('roles', '0005_alter_member_unique_together'),
        ('memberscan', '0002_alter_memberscan_date_time_alter_memberscan_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=19)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.member')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.shift')),
            ],
        ),
        migrations.AddField(
            model_name='memberscan',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memberscan.attendance'),
        ),
    ]
