# Generated by Django 4.2.4 on 2023-08-23 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberscan', '0004_alter_memberscan_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberscan',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memberscan.attendance'),
        ),
    ]
