# Generated by Django 4.2.4 on 2023-08-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberscan', '0005_alter_memberscan_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default='2023-08-24'),
            preserve_default=False,
        ),
    ]
