# Generated by Django 4.2.4 on 2023-08-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberscan', '0006_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberscan',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
