# Generated by Django 4.2.4 on 2023-08-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberscan', '0007_alter_memberscan_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberscan',
            options={'ordering': ['-created_at']},
        ),
    ]
