# Generated by Django 4.2.4 on 2023-08-16 06:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0002_alter_member_organization'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('enable_face_recognition', models.BooleanField(default=True)),
                ('enable_geo_fencing', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=15)),
                ('shift_start_time_restriction', models.BooleanField(default=True)),
                ('loc_settings_start_time_restriction', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift', to='roles.member')),
                ('default_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift', to='location.systemlocation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift', to='roles.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_shift', to='roles.member')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftScheduleLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_settings', models.ManyToManyField(related_name='shiftschedulelog', to='location.locationsettings')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftschedulelog', to='roles.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftschedulelog', to='roles.organization')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftschedulelog', to='shift.shift')),
            ],
        ),
    ]
