# Generated by Django 4.2.4 on 2023-08-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_member_organization'),
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftschedulelog',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shiftschedulelog', to='roles.member'),
        ),
    ]
