# Generated by Django 4.2.4 on 2023-08-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('shift', '0002_alter_shiftschedulelog_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftschedulelog',
            name='location_settings',
            field=models.ManyToManyField(blank=True, null=True, related_name='shiftschedulelog', to='location.locationsettings'),
        ),
    ]
