# Generated by Django 4.2.4 on 2023-08-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_alter_member_unique_together'),
        ('shift', '0004_alter_shiftschedulelog_location_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='crone_job',
            field=models.TimeField(default='10:00:00'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('name', 'organization')},
        ),
    ]
