# Generated by Django 4.2.4 on 2023-08-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0005_shift_crone_job_alter_shift_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedulelog',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='shiftschedulelog',
            name='start_date',
            field=models.DateField(default='2023-08-08'),
            preserve_default=False,
        ),
    ]
