# Generated by Django 4.2.4 on 2023-08-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0007_organization_shift_default'),
        ('shift', '0006_shiftschedulelog_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftschedulelog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftschedulelog', to='roles.member'),
        ),
    ]
