# Generated by Django 4.2.4 on 2023-08-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0007_alter_shiftschedulelog_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftschedulelog',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
