# Generated by Django 4.2.4 on 2023-09-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0008_alter_shiftschedulelog_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftschedulelog',
            options={'ordering': ['start_date']},
        ),
    ]
