# Generated by Django 4.2.4 on 2023-08-28 07:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_alter_member_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.JSONField()),
                ('path', models.CharField(null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], max_length=25)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportrequest', to='roles.member')),
            ],
        ),
    ]
