# Generated by Django 4.2.4 on 2023-08-30 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0006_shiftschedulelog_end_date_and_more'),
        ('roles', '0006_exportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='shift_default',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_shift', to='shift.shift'),
        ),
    ]
